### ISSUE TITLE
dump file will cover when I have multi-files

### ISSUE THREAD

**Issue by hank7444** [mrhooray/gulp-mocha-phantomjs#27]
Hi!

I would like to test multi-files,

for example, 

test_mocha_html folder have 2 files, call a.html & b.html

when I ran gulp, I found xunit.xml content b will replace a, 
I would like to get all files testing result in one file for Jenkins, is it any way to do this? thx!

my gulp script as follow:

```
gulp.task('test', function() {
    return gulp.src('./test_mocha_html/**/*.html')
        .pipe(plumber())
        .pipe(mochaPhantomJS({
            webSecurityEnabled: false,
            outputEncoding: 'utf8',
            localToRemoteUrlAccessEnabled: true,
            reporter: 'xunit',
            dump: 'xunit.xml'
        }))
    //.pipe(notify({ message: 'tests finished'}))
    .on('error', handleError);
});
```

**Comment by mrhooray** [comment]
indeed an issue, would multiple files work for you? seems xml file does not allow multiple root elements

**Comment by mrhooray** [comment]
or you could simply pipe the stdout of test into somewhere else

**Comment by mrhooray** [comment]
anyway, xml or not does not matter, it's just output dump

updated with append mode, please use latest master
