### ISSUE TITLE
when testing multiple files, halt on first failure

### ISSUE THREAD

**Issue by nicholascloud** [mrhooray/gulp-mocha-phantomjs#28]
When testing multiple files, I would like to be able to tell the test runner to halt on the first failure. My gulp task looks like this:

```javascript
gulp.task('test:scripts', function () {
    var globs = [
        '**/*.test.html',
        '!**/test-template.test.html'
    ];

    return gulp.src(globs, {base: 'tests'})
        .pipe(gulpMochaPhantom({
            reporter: 'spec',
            silent: false
        }));
});
```

I have 10 tests and test 5 fails, but the test runner continues to run tests 6 - 10. Sometimes this is desirable behavior, but other times I would like to halt immediately, fix an offending test, then try again.

**Comment by mrhooray** [comment]
currently it should bail out on first file that contains failed tests

if you are talking about bail out on first failed test, mocha on the client side seems do not support this. it only supports [grep related options](https://github.com/mochajs/mocha/blob/994e65efd629360f90e7f1680d88350e4b5aff92/support/tail.js#L141-L144)

**Comment by nicholascloud** [comment]
currently it should bail out on first file that contains failed tests

@mrhooray that is not the behavior I am seeing. When a test file fails, it continues to process subsequent test files. Do I need to pass some option to the gulp-mocha-phantomjs plugin to enable this?

Here is a screenshot of what I see: 

![failed test does not halt testing](https://i.imgur.com/dyrxKJW.png)

**Comment by mrhooray** [comment]
@nicholascloud cool, latest master should fix this problem

**Comment by nicholascloud** [comment]
@mrhooray Excellent. Just tried it out and it works as expected, thanks!
