### ISSUE TITLE
Exectuting External JS scripts

### ISSUE THREAD

**Issue by cmata23x3** [mrhooray/gulp-mocha-phantomjs#29]
I'm having issues with executing external JS scripts in the test runner HTML file. I add a `<script src='./tests.js'></script>` tag into the HTML file, but issues occur with attempting to exectue those files. When the gulp task runs, an error occurs and the stack returns 
`TypeError: 'undefined' is not an object (evaluating 'expect(true).should.equal')
      at file:///Users/me/project/test/client/bundle.js:39
      at callFn (file:///Users/me/project/node_modules/mocha/mocha.js:4562)
      at file:///Users/me/project/ResourceCollector/node_modules/mocha/mocha.js:4555
      at file:///Users/me/project/node_modules/mocha/mocha.js:4974
      at file:///Users/christianmata/Desktop/OpenDesign/ResourceCollector/node_modules/mocha/mocha.js:5079
      at next (file:///Users/me/project/node_modules/mocha/mocha.js:4899)
      at file:///Users/me/project/node_modules/mocha/mocha.js:4909
      at next (file:///Users/me/project/node_modules/mocha/mocha.js:4844)
      at file:///Users/me/project/node_modules/mocha/mocha.js:4876
      at timeslice (file:///Users/me/project/node_modules/mocha/mocha.js:6483)`

I looked through the test cases that exist in the repo and none of them try loading in other scripts, so maybe this issue has went through the testing suite.

**Comment by mrhooray** [comment]
could you provide a concrete example to reproduce your problem?
