### ISSUE TITLE
Colorful output

### ISSUE THREAD

**Issue by pronebird** [mrhooray/gulp-mocha-phantomjs#31]
Did you experience a problem of complete absence of colors in terminal? I can't find the way to workaround that problem. Gulp output is colorful though.

I tried using useColors flag but with no luck..

```js
gulp.task('test', function () {
	return gulp.src('tests/runner.html')
    	.pipe( mochaPhantomJS({ 
    		reporter: 'spec',
    		mocha: { 
    			useColors: true
    		}
    	}) );
});
```

**Comment by pronebird** [comment]
Nevermind, rollback to Mocha ~1.x solved this for me...

**Comment by georgschlenkhoff** [comment]
Same problem here. Would like to work with newer version. Any update on this?

**Comment by nathanboktae** [comment]
Actually you need to use it via mocha-phantomjs's options:

```
phantomjs: {
  useColors: true
}
```

This should be documented.
