### ISSUE TITLE
Option to suppress console output

### ISSUE THREAD

**Issue by Mr0grog** [mrhooray/gulp-mocha-phantomjs#33]
It would be pretty nice if there was an option to prevent output to stdout/stderr. That way, users can manage the output themselves using the stream this module returns.

For example, in a build process I’m currently working with, I’d like to suppress output if there are no test failures. Unfortunately I can’t actually do that because the phantomjs output is always piped to stdout no matter what: https://github.com/mrhooray/gulp-mocha-phantomjs/blob/master/index.js#L67

**Comment by mrhooray** [comment]
@Mr0grog 
just added support for suppressing output in v0.9.0
```
    if (!options.suppressStdout) {
        phantomjs.stdout.pipe(process.stdout);
    }

    if (!options.suppressStderr) {
        phantomjs.stderr.pipe(process.stderr);
    }

```

**Comment by Mr0grog** [comment]
Sweet, thank you so much! (Sorry for the *very* late reply; I’ve been on a long bicycle trip and this is the first time I’ve had a computer in a couple months.)

Do you mind if I submit a PR to document `suppressStdout` & `suppressStderr`?
