### ISSUE TITLE
mocha-phantomjs phantom version is being limited to 1.9.15

### ISSUE THREAD

**Issue by njprrogers** [mrhooray/gulp-mocha-phantomjs#36]
The mocha-phantomjs owner has changed their package.json to limit phantomjs to 1.9.1 - 1.9.7-15. Currently, gulp-mocha-phantomjs is pulling in 1.9.17 which is breaking our build :(
I've reached out to ask for a more liberal range for phantomjs but I assume that it is being done on purpose (https://github.com/nathanboktae/mocha-phantomjs/commit/4390a064afe6986c5f41c15cd56f2666f36eca02) as it has been re-applied on the most recent commit at https://github.com/nathanboktae/mocha-phantomjs/blob/master/package.json. 
If that is the case, we might need to make a change here to limit phantomjs to 1.9.1 - 1.9.7-15 as well.

Thanks!
N

**Comment by jfbibeau** [comment]
Yep! Affecting me here as well starting today, I can no longer install gulp-mocha-phantomjs. Any chance of a quick fix?

**Comment by tjfroll** [comment]
Also a problem for me - had to disable unit tests to successfully build.  Problematic!

**Comment by MattKunze** [comment]
Adding an explicit dependency to mocha-phantomjs@3.6.0 to my project works around it for me. Someone also posted a fix-gulp-mocha-phantomjs project to npm, but I'd rather not commit that change

**Comment by tjfroll** [comment]
Thanks for the tip @MattKunze - build works again.  I'd previously been trying to manually set the phantomjs version to 1.9.7-15 without success.

**Comment by mrhooray** [comment]
#34 has been merged and v0.7.0 was published

**Comment by mrhooray** [comment]
this plugin has been updated to use mocha-phantomjs-core which doesn't have peerDependency on phantomjs and went back using caret prefix, new version has been published
