### ISSUE TITLE
The package phantomjs does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by dmfilipenko** [mrhooray/gulp-mocha-phantomjs#40]
Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15 

and as of npm@2.0.0 (which introduced semver@4) pre-releases no longer satisfy that semver range.

**Comment by dmfilipenko** [comment]
@mrhooray

**Comment by mrhooray** [comment]
@dmfilipenko this plugin has been updated to use on mocha-phantomjs-core which has no (peer)dependency on phantomjs

could you try using v0.8.1?

**Comment by thenickcox** [comment]
I ran into this issue, too, and using v0.8.1 fixed it.
