### ISSUE TITLE
Missing file doesn't trigger error

### ISSUE THREAD

**Issue by rjmunro** [mrhooray/gulp-mocha-phantomjs#42]
I have a task like:
```
gulp.task('test-unit', function() {
  return gulp
  .src('test/unit/local.html')
  .pipe(mochaPhantomJS());
});
```

If the file `test/unit/local.html` doesn't exist, and I run `gulp test-unit` the tests don't fail in an obvious way (I'd expect to see `Error in plugin 'gulp-mocha-phantomjs'` and a non-zero exit code).

I had a typo in the filename, and that meant my tests were all passing on CI, when in fact, they just weren't being run. This seems like undesirable behaviour.

**Comment by mrhooray** [comment]
gulp.src returns a stream of files match the glob pattern you provides and this plugin simplify operates on that stream even if it's empty

i don't think this plugin should assert that the stream is not empty; you might want to use a steam that checks for at least one match before piping into this plugin
