### ISSUE TITLE
How to Call Phantom Functions and Clear Heap

### ISSUE THREAD

**Issue by Caf131** [mrhooray/gulp-mocha-phantomjs#43]
Hello, thanks for creating this module.  I would like to know how to call the PhantomJS functions, such as "addCookie()", "clearCookie()"...Also, how would I go about clearing the memory/heap.

**Comment by mrhooray** [comment]
this plugin depends on [mocha-phantomjs-core](https://github.com/nathanboktae/mocha-phantomjs-core) as phanomjs script; i don't think it allows calling phantomjs function directly from the page

however it seems to support [adding cookies](https://github.com/nathanboktae/mocha-phantomjs-core/blob/master/mocha-phantomjs-core.js#L57-L59) so you could try something like
```js
gulp.task('test', function () {
    return gulp
    .src('test/runner.html')
    .pipe(mochaPhantomJS({
        phantomjs: {
            cookies: [...]
        }
    }));
});
```
