### ISSUE TITLE
Can't find variable Mocha in browser-shim.js (mocha-phantomjs-core)

### ISSUE THREAD

**Issue by straker** [mrhooray/gulp-mocha-phantomjs#49]
I get an error when running the basic code that node can't find the variable `Mocha`.

```
ReferenceError: Can't find variable: Mocha

   at browser-shim.js:27
```

I'm not sure if it's your code calling mocha-phantomjs-core that's the problem or mocha-phantomjs-core itself. If you could point me in the right direction, that'd be great.

You can see my code at https://github.com/straker/kontra/tree/codeCoverage. Runner file is in `test/runner.html`. If you bring up the runner file in a browser, the page is fine and all tests run and pass.

**Comment by MeoMix** [comment]
This is because mocha changed from "Mocha" to "mocha" in 1.4.2.

**Comment by straker** [comment]
@MeoMix I have Mocha 2.3.2 installed, and from their code it looks like they are [exposing](https://github.com/mochajs/mocha/blob/v2.3.2/mocha.js#L12291) Mocha and mocha. If I go to my `test/runner.html` page in a browser, both Mocha and mocha are there. 

From mocha-phantomjs-core [code](https://github.com/nathanboktae/mocha-phantomjs-core/blob/master/mocha-phantomjs-core.js#L85), it looks like they navigate to the webpage and if a resource called `mocha.js` is loaded, it loads the `browser-shim.js` file into the page. But at that point, only `mocha` exists, not `Mocha`, so I don't know what's going on.

**Comment by MeoMix** [comment]
I only say this because the grunt-mocha plugin specifically anticipates Mocha not existing: https://github.com/kmiyashiro/grunt-mocha/blob/master/phantomjs/bridge.js#L39

**Comment by mrhooray** [comment]
@straker https://github.com/straker/kontra/tree/codeCoverage is not accessible any more
from the conversation, looks like your problem has been resolved?

**Comment by straker** [comment]
I went a different route since I couldn't get it to work and got karma-coverage.
