### ISSUE TITLE
PhantomJS 1.9.8?

### ISSUE THREAD

**Issue by erwan** [mrhooray/gulp-mocha-phantomjs#50]
I see in #24 that switching to PhantomJS 2.0 is not for right now.

Can we at least get PhantomJS 1.9.8? For example it uses TLS by default, meaning that we can fetch all the https domains that were changed after POODLE.

**Comment by vlimjap** [comment]
It also becomes an issue when I run this using Node4.0+.
Versions below that are fine.

**Comment by mrhooray** [comment]
released v0.11.0 with phantomjs 2 and updated deps
will release v1.0.0 some time later if no critical issues
