### ISSUE TITLE
Error when trying to install (nodejs 4.2.1, npm 3.3.8)

### ISSUE THREAD

**Issue by doberkofler** [mrhooray/gulp-mocha-phantomjs#52]
When trying to install `gulp-mocha-pantomjs` on Windows using node 4.2.1 and npm 3.3.8,  I get the following error message:

```
>npm install gulp-mocha-phantomjs

> phantomjs@1.9.7-15 install D:\MyDev\ljs_app\trunk\periscope\build\node_modules\phantomjs
> node install.js

Download already available at C:\Users\DOBERK~1.LBI\AppData\Local\Temp\phantomjs\phantomjs-1.9.7-windows.zip
Extracting zip contents
Copying extracted folder C:\Users\DOBERK~1.LBI\AppData\Local\Temp\phantomjs\phantomjs-1.9.7-windows.zip-extract-1445404958420\phantomjs-1.9.7-windows -> D:\MyDe
v\ljs_app\trunk\periscope\build\node_modules\phantomjs\lib\phantom
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, open 'C:\Users\DOBERK~1.LBI\AppData\Local\Temp\phantomjs\phantomjs-1.9.7-windows.zip-extract-1445404958420\phantomjs-1.9.
7-windows\phantomjs.exe'
    at Error (native)
```

**Comment by doberkofler** [comment]
It seems to be an issue https://github.com/Medium/phantomjs/issues/399 with phantomjs

**Comment by icfront** [comment]
has anyone found a fix for this issue?

**Comment by doberkofler** [comment]
@icfront with current versions the problem is solved

**Comment by icfront** [comment]
Thanks @doberkofler - I updated npm to latest version v3.4.1 with node at v4.2.1 and getting the following error:

    npm WARN EPACKAGEJSON poppi-sass@1.0.0 No repository field.
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppDa
    ta\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-uncss" "--
    save-dev"
    npm ERR! node v4.2.1
    npm ERR! npm  v3.4.1
    npm ERR! code ELIFECYCLE

    npm ERR! phantomjs@1.9.19 install: `node install.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the phantomjs package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node install.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls phantomjs
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Project-folder\Project\npm-debug.log

I can send the npm-debug.log too if needed. Thanks

**Comment by doberkofler** [comment]
@icfront Sometimes it helps to complete remove the node_modules directory clear the npm cache and reinstall all needed modules.
