### ISSUE TITLE
color in cli

### ISSUE THREAD

**Issue by barsukov** [mrhooray/gulp-mocha-phantomjs#53]
AM I only one does not have any colors in cli? if yes why? :)
For failed task is the same.
<img width="368" alt="screenshot 2015-11-25 09 41 01" src="https://cloud.githubusercontent.com/assets/1594996/11392240/a92d09b6-9358-11e5-9654-8ac8bc426b83.png">

**Comment by 06wj** [comment]
you can set useColors  to true
```
gulp .src('test/html/index.html')
        .pipe(mochaPhantomJS({
            reporter:'spec',
            phantomjs: {
                viewportSize: {
                    width: 1024,
                    height: 768
                },
                useColors:true
            }
        }));
```

**Comment by barsukov** [comment]
Thank u I was tried as well but without ``phantomjs: {}`` arounding. It is working for me thank u very much, but if u add it to doku it would be great
