### ISSUE TITLE
Broken after updating to Mocha v2.4.*

### ISSUE THREAD

**Issue by adambiggs** [mrhooray/gulp-mocha-phantomjs#57]
After updating Mocha from v2.3.4 to v2.4.4, `gulp-mocha-phantomjs` hangs without any output.

I noticed that downgrading to Mocha v2.4.1 gives *some* cli output, but instead of the usual `dot` reporter output I get a bunch of empty lines in the console.

**Comment by mrhooray** [comment]
mocha 2.4.5 works fine with tests of this module
maybe try clean install of dependencies?

if it still happens, could you provide a reproduce repo for this issue?

**Comment by adambiggs** [comment]
I couldn't reproduce this after updating to v0.11.0... Not sure if the update fixed it or if it was something else on my end.

I'll report back if it happens again.
