### ISSUE TITLE
Is there a way to use globally installed phantomjs binary?

### ISSUE THREAD

**Issue by adambiggs** [mrhooray/gulp-mocha-phantomjs#60]
Our team develops with Docker, and our standard workflow is to run tests inside a Docker container.

But sometimes it'd be nice to have the option of running tests in OSX because they run a bit quicker... But currently this isn't easy because the debian `phantomjs` binary is installed locally.

It would be cool if there was a way to tell `gulp-mocha-phantomjs` to use the `phantomjs` binary I have installed globally in OSX with a cli option of some kind.

Anybody know if this is possible?

**Comment by mrhooray** [comment]
do you mean having tests running inside docker container using phantomjs installed on host machine/your OSX environment?
