### ISSUE TITLE
version 0.11.0?

### ISSUE THREAD

**Issue by ahamid** [mrhooray/gulp-mocha-phantomjs#67]
According to npm package repository `0.11.0` is the latest release, however i don't see a `0.11.0` tag in this repo.  Can you confirm master reflects the `0.11.0` release? I ask because I just upgraded from `0.10.1` to `0.11.0` and am seeing a runaway memory consumption problem, but want to confirm version first.

**Comment by philwhln** [comment]
I noticed this too. Package.json in master does say `0.11.0`

**Comment by mrhooray** [comment]
@ahamid v0.11.0 is 98084ae5ecd457f74e2c3a5bae78426e2f84cc92 and I just push the tag to github remote

**Comment by philwhln** [comment]
thanks!
