### ISSUE TITLE
example   Test against remote by url error

### ISSUE THREAD

**Issue by 534591395** [mrhooray/gulp-mocha-phantomjs#75]
stream.write({path: 'http://localhost:8000/index.html'});    run error 
find in index.js    toURl  `if (['http:', 'https:', 'file:'].indexOf(parsed.protocol) > 0) {`  error
`if (['http:', 'https:', 'file:'].indexOf(parsed.protocol) > -1) {`  true

**Comment by mh-cbon** [comment]
@mrhooray ?

**Comment by MrSwitch** [comment]
This was merged in September 2016, https://github.com/mrhooray/gulp-mocha-phantomjs/pull/74/files

And needs a bump and deploy

**Comment by mrhooray** [comment]
sorry for the delay and published patched version. please reopen if above fix doesn't resolve the issue
